<?php
/**
 * EmailDesignSetsApi
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nmusco\AssureSign\v3\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Nmusco\AssureSign\v3\ApiException;
use Nmusco\AssureSign\v3\Configuration;
use Nmusco\AssureSign\v3\HeaderSelector;
use Nmusco\AssureSign\v3\ObjectSerializer;

/**
 * EmailDesignSetsApi Class Doc Comment
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmailDesignSetsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getDefaultNotifications
     *
     * Retrieve all default notifications
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (required)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getDefaultNotifications($emailDesignSetID, $culture, $xASUserContext = null)
    {
        list($response) = $this->getDefaultNotificationsWithHttpInfo($emailDesignSetID, $culture, $xASUserContext);
        return $response;
    }

    /**
     * Operation getDefaultNotificationsWithHttpInfo
     *
     * Retrieve all default notifications
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (required)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDefaultNotificationsWithHttpInfo($emailDesignSetID, $culture, $xASUserContext = null)
    {
        $request = $this->getDefaultNotificationsRequest($emailDesignSetID, $culture, $xASUserContext);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDefaultNotificationsAsync
     *
     * Retrieve all default notifications
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (required)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDefaultNotificationsAsync($emailDesignSetID, $culture, $xASUserContext = null)
    {
        return $this->getDefaultNotificationsAsyncWithHttpInfo($emailDesignSetID, $culture, $xASUserContext)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDefaultNotificationsAsyncWithHttpInfo
     *
     * Retrieve all default notifications
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (required)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDefaultNotificationsAsyncWithHttpInfo($emailDesignSetID, $culture, $xASUserContext = null)
    {
        $returnType = 'object';
        $request = $this->getDefaultNotificationsRequest($emailDesignSetID, $culture, $xASUserContext);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDefaultNotifications'
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (required)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getDefaultNotificationsRequest($emailDesignSetID, $culture, $xASUserContext = null)
    {
        // verify the required parameter 'emailDesignSetID' is set
        if ($emailDesignSetID === null || (is_array($emailDesignSetID) && count($emailDesignSetID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $emailDesignSetID when calling getDefaultNotifications'
            );
        }
        // verify the required parameter 'culture' is set
        if ($culture === null || (is_array($culture) && count($culture) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $culture when calling getDefaultNotifications'
            );
        }

        $resourcePath = '/emaildesignsets/{emailDesignSetID}/defaultEmailNotifications/{culture}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($xASUserContext !== null) {
            $headerParams['X-AS-UserContext'] = ObjectSerializer::toHeaderValue($xASUserContext);
        }

        // path params
        if ($emailDesignSetID !== null) {
            $resourcePath = str_replace(
                '{' . 'emailDesignSetID' . '}',
                ObjectSerializer::toPathValue($emailDesignSetID),
                $resourcePath
            );
        }
        // path params
        if ($culture !== null) {
            $resourcePath = str_replace(
                '{' . 'culture' . '}',
                ObjectSerializer::toPathValue($culture),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEmailDesignSets
     *
     * Retrieve all email design sets for a given account
     *
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesignSets Specifies whether or not to include built-in design sets.  To query a specific built-in design set, include the culture (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getEmailDesignSets($culture = null, $includeSystemDesignSets = null, $xASUserContext = null)
    {
        list($response) = $this->getEmailDesignSetsWithHttpInfo($culture, $includeSystemDesignSets, $xASUserContext);
        return $response;
    }

    /**
     * Operation getEmailDesignSetsWithHttpInfo
     *
     * Retrieve all email design sets for a given account
     *
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesignSets Specifies whether or not to include built-in design sets.  To query a specific built-in design set, include the culture (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEmailDesignSetsWithHttpInfo($culture = null, $includeSystemDesignSets = null, $xASUserContext = null)
    {
        $request = $this->getEmailDesignSetsRequest($culture, $includeSystemDesignSets, $xASUserContext);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEmailDesignSetsAsync
     *
     * Retrieve all email design sets for a given account
     *
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesignSets Specifies whether or not to include built-in design sets.  To query a specific built-in design set, include the culture (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEmailDesignSetsAsync($culture = null, $includeSystemDesignSets = null, $xASUserContext = null)
    {
        return $this->getEmailDesignSetsAsyncWithHttpInfo($culture, $includeSystemDesignSets, $xASUserContext)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEmailDesignSetsAsyncWithHttpInfo
     *
     * Retrieve all email design sets for a given account
     *
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesignSets Specifies whether or not to include built-in design sets.  To query a specific built-in design set, include the culture (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEmailDesignSetsAsyncWithHttpInfo($culture = null, $includeSystemDesignSets = null, $xASUserContext = null)
    {
        $returnType = 'object';
        $request = $this->getEmailDesignSetsRequest($culture, $includeSystemDesignSets, $xASUserContext);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEmailDesignSets'
     *
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesignSets Specifies whether or not to include built-in design sets.  To query a specific built-in design set, include the culture (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEmailDesignSetsRequest($culture = null, $includeSystemDesignSets = null, $xASUserContext = null)
    {

        $resourcePath = '/emaildesignsets';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($culture !== null) {
            $queryParams['culture'] = ObjectSerializer::toQueryValue($culture);
        }
        // query params
        if ($includeSystemDesignSets !== null) {
            $queryParams['IncludeSystemDesignSets'] = ObjectSerializer::toQueryValue($includeSystemDesignSets);
        }
        // header params
        if ($xASUserContext !== null) {
            $headerParams['X-AS-UserContext'] = ObjectSerializer::toHeaderValue($xASUserContext);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getEmailDesigns
     *
     * Retrieve all email designs for a given email design set
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesigns includeSystemDesigns (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function getEmailDesigns($emailDesignSetID, $culture = null, $includeSystemDesigns = null, $xASUserContext = null)
    {
        list($response) = $this->getEmailDesignsWithHttpInfo($emailDesignSetID, $culture, $includeSystemDesigns, $xASUserContext);
        return $response;
    }

    /**
     * Operation getEmailDesignsWithHttpInfo
     *
     * Retrieve all email designs for a given email design set
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesigns (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \Nmusco\AssureSign\v3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function getEmailDesignsWithHttpInfo($emailDesignSetID, $culture = null, $includeSystemDesigns = null, $xASUserContext = null)
    {
        $request = $this->getEmailDesignsRequest($emailDesignSetID, $culture, $includeSystemDesigns, $xASUserContext);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getEmailDesignsAsync
     *
     * Retrieve all email designs for a given email design set
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesigns (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEmailDesignsAsync($emailDesignSetID, $culture = null, $includeSystemDesigns = null, $xASUserContext = null)
    {
        return $this->getEmailDesignsAsyncWithHttpInfo($emailDesignSetID, $culture, $includeSystemDesigns, $xASUserContext)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getEmailDesignsAsyncWithHttpInfo
     *
     * Retrieve all email designs for a given email design set
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesigns (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getEmailDesignsAsyncWithHttpInfo($emailDesignSetID, $culture = null, $includeSystemDesigns = null, $xASUserContext = null)
    {
        $returnType = 'object';
        $request = $this->getEmailDesignsRequest($emailDesignSetID, $culture, $includeSystemDesigns, $xASUserContext);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getEmailDesigns'
     *
     * @param  string $emailDesignSetID Specifies the unique identifier of the email design set (required)
     * @param  string $culture Specifies which culture to use when including system designs. Currently supported cultures are: en‑US (English - US), es‑US (Spanish - US), and fr‑CA (French - Canada) (optional)
     * @param  bool $includeSystemDesigns (optional)
     * @param  string $xASUserContext {username}:{DocumentNOW Account Context Identifier} (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getEmailDesignsRequest($emailDesignSetID, $culture = null, $includeSystemDesigns = null, $xASUserContext = null)
    {
        // verify the required parameter 'emailDesignSetID' is set
        if ($emailDesignSetID === null || (is_array($emailDesignSetID) && count($emailDesignSetID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $emailDesignSetID when calling getEmailDesigns'
            );
        }

        $resourcePath = '/emaildesignsets/{emailDesignSetID}/emailDesigns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($culture !== null) {
            $queryParams['culture'] = ObjectSerializer::toQueryValue($culture);
        }
        // query params
        if ($includeSystemDesigns !== null) {
            $queryParams['IncludeSystemDesigns'] = ObjectSerializer::toQueryValue($includeSystemDesigns);
        }
        // header params
        if ($xASUserContext !== null) {
            $headerParams['X-AS-UserContext'] = ObjectSerializer::toHeaderValue($xASUserContext);
        }

        // path params
        if ($emailDesignSetID !== null) {
            $resourcePath = str_replace(
                '{' . 'emailDesignSetID' . '}',
                ObjectSerializer::toPathValue($emailDesignSetID),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
