<?php
/**
 * SigningLink
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Nmusco\AssureSign\v3\Model;

use \ArrayAccess;
use \Nmusco\AssureSign\v3\ObjectSerializer;

/**
 * SigningLink Class Doc Comment
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SigningLink implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'signingLink';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'envelopeID' => 'string',
        'signatoryEmail' => 'string',
        'signatoryMobilePhone' => 'string',
        'url' => 'string',
        'expirationDate' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'envelopeID' => 'uuid',
        'signatoryEmail' => 'email',
        'signatoryMobilePhone' => null,
        'url' => null,
        'expirationDate' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'envelopeID' => 'envelopeID',
        'signatoryEmail' => 'signatoryEmail',
        'signatoryMobilePhone' => 'signatoryMobilePhone',
        'url' => 'url',
        'expirationDate' => 'expirationDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'envelopeID' => 'setEnvelopeID',
        'signatoryEmail' => 'setSignatoryEmail',
        'signatoryMobilePhone' => 'setSignatoryMobilePhone',
        'url' => 'setUrl',
        'expirationDate' => 'setExpirationDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'envelopeID' => 'getEnvelopeID',
        'signatoryEmail' => 'getSignatoryEmail',
        'signatoryMobilePhone' => 'getSignatoryMobilePhone',
        'url' => 'getUrl',
        'expirationDate' => 'getExpirationDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['envelopeID'] = isset($data['envelopeID']) ? $data['envelopeID'] : null;
        $this->container['signatoryEmail'] = isset($data['signatoryEmail']) ? $data['signatoryEmail'] : null;
        $this->container['signatoryMobilePhone'] = isset($data['signatoryMobilePhone']) ? $data['signatoryMobilePhone'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['expirationDate'] = isset($data['expirationDate']) ? $data['expirationDate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets envelopeID
     *
     * @return string|null
     */
    public function getEnvelopeID()
    {
        return $this->container['envelopeID'];
    }

    /**
     * Sets envelopeID
     *
     * @param string|null $envelopeID envelopeID
     *
     * @return $this
     */
    public function setEnvelopeID($envelopeID)
    {
        $this->container['envelopeID'] = $envelopeID;

        return $this;
    }

    /**
     * Gets signatoryEmail
     *
     * @return string|null
     */
    public function getSignatoryEmail()
    {
        return $this->container['signatoryEmail'];
    }

    /**
     * Sets signatoryEmail
     *
     * @param string|null $signatoryEmail signatoryEmail
     *
     * @return $this
     */
    public function setSignatoryEmail($signatoryEmail)
    {
        $this->container['signatoryEmail'] = $signatoryEmail;

        return $this;
    }

    /**
     * Gets signatoryMobilePhone
     *
     * @return string|null
     */
    public function getSignatoryMobilePhone()
    {
        return $this->container['signatoryMobilePhone'];
    }

    /**
     * Sets signatoryMobilePhone
     *
     * @param string|null $signatoryMobilePhone signatoryMobilePhone
     *
     * @return $this
     */
    public function setSignatoryMobilePhone($signatoryMobilePhone)
    {
        $this->container['signatoryMobilePhone'] = $signatoryMobilePhone;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets expirationDate
     *
     * @return \DateTime|null
     */
    public function getExpirationDate()
    {
        return $this->container['expirationDate'];
    }

    /**
     * Sets expirationDate
     *
     * @param \DateTime|null $expirationDate expirationDate
     *
     * @return $this
     */
    public function setExpirationDate($expirationDate)
    {
        $this->container['expirationDate'] = $expirationDate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


