<?php
/**
 * DocumentApiModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nmusco\AssureSign\v3;

use PHPUnit\Framework\TestCase;

/**
 * DocumentApiModelTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentApiModel
 * @package     Nmusco\AssureSign\v3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentApiModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentApiModel"
     */
    public function testDocumentApiModel()
    {
    }

    /**
     * Test attribute "additionalAgreement"
     */
    public function testPropertyAdditionalAgreement()
    {
    }

    /**
     * Test attribute "additionalDisclosures"
     */
    public function testPropertyAdditionalDisclosures()
    {
    }

    /**
     * Test attribute "additionalTerms"
     */
    public function testPropertyAdditionalTerms()
    {
    }

    /**
     * Test attribute "cultureType"
     */
    public function testPropertyCultureType()
    {
    }

    /**
     * Test attribute "documentID"
     */
    public function testPropertyDocumentID()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "fileExtension"
     */
    public function testPropertyFileExtension()
    {
    }

    /**
     * Test attribute "pageCount"
     */
    public function testPropertyPageCount()
    {
    }

    /**
     * Test attribute "signingDeviceEnabled"
     */
    public function testPropertySigningDeviceEnabled()
    {
    }

    /**
     * Test attribute "isFinalized"
     */
    public function testPropertyIsFinalized()
    {
    }

    /**
     * Test attribute "completionDate"
     */
    public function testPropertyCompletionDate()
    {
    }

    /**
     * Test attribute "declinedDate"
     */
    public function testPropertyDeclinedDate()
    {
    }
}
