<?php
/**
 * EmailDesignSetDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nmusco\AssureSign\v3;

use PHPUnit\Framework\TestCase;

/**
 * EmailDesignSetDtoTest Class Doc Comment
 *
 * @category    Class
 * @description EmailDesignSetDto
 * @package     Nmusco\AssureSign\v3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EmailDesignSetDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailDesignSetDto"
     */
    public function testEmailDesignSetDto()
    {
    }

    /**
     * Test attribute "accountId"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "culture"
     */
    public function testPropertyCulture()
    {
    }

    /**
     * Test attribute "dateCreated"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "dateModified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "isAccountDefault"
     */
    public function testPropertyIsAccountDefault()
    {
    }

    /**
     * Test attribute "isSystem"
     */
    public function testPropertyIsSystem()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "systemId"
     */
    public function testPropertySystemId()
    {
    }

    /**
     * Test attribute "originalID"
     */
    public function testPropertyOriginalID()
    {
    }
}
