<?php
/**
 * EnvelopeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Nmusco\AssureSign\v3;

use PHPUnit\Framework\TestCase;

/**
 * EnvelopeTest Class Doc Comment
 *
 * @category    Class
 * @description Envelope
 * @package     Nmusco\AssureSign\v3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EnvelopeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Envelope"
     */
    public function testEnvelope()
    {
    }

    /**
     * Test attribute "cultureType"
     */
    public function testPropertyCultureType()
    {
    }

    /**
     * Test attribute "declineBehaviorType"
     */
    public function testPropertyDeclineBehaviorType()
    {
    }

    /**
     * Test attribute "downloadPassword"
     */
    public function testPropertyDownloadPassword()
    {
    }

    /**
     * Test attribute "expirationDate"
     */
    public function testPropertyExpirationDate()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "orderID"
     */
    public function testPropertyOrderID()
    {
    }

    /**
     * Test attribute "signingDeviceEnabled"
     */
    public function testPropertySigningDeviceEnabled()
    {
    }

    /**
     * Test attribute "viewBehaviorType"
     */
    public function testPropertyViewBehaviorType()
    {
    }

    /**
     * Test attribute "workflowType"
     */
    public function testPropertyWorkflowType()
    {
    }

    /**
     * Test attribute "allowInPersonSigning"
     */
    public function testPropertyAllowInPersonSigning()
    {
    }

    /**
     * Test attribute "redirectUrl"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "termsAndConditions"
     */
    public function testPropertyTermsAndConditions()
    {
    }
}
