<?php
/**
 * PreparedEnvelopeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssureSign DocumentNOW API Documentation
 *
 * <h2>AssureSign DocumentNOW electronic signature APIs (envelopes and documents)</h2><h3>For DocumentNOW user and account management APIs, go to [Account API](https://account.assuresign.net/api/v3.6/account)</h3>
 *
 * The version of the OpenAPI document: 3.6
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Nmusco\AssureSign\v3;

use \Nmusco\AssureSign\v3\Configuration;
use \Nmusco\AssureSign\v3\ApiException;
use \Nmusco\AssureSign\v3\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PreparedEnvelopeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Nmusco\AssureSign\v3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PreparedEnvelopeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPreparedEnvelope
     *
     * Prepare an envelope for additional operations, including manual review and adding documents.
     *
     */
    public function testCreatePreparedEnvelope()
    {
    }

    /**
     * Test case for updatePreparedEnvelope
     *
     * Perform additional operations on a previously created prepared envelope.
     *
     */
    public function testUpdatePreparedEnvelope()
    {
    }
}
